apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-backend.fullname" . }}-secret
  labels:
    {{- include "flask-backend.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
