apiVersion: v2
name: gough
description: A Helm chart for Gough Hypervisor Automation System - Enterprise HA deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/penguintechinc/gough
maintainers:
  - name: Penguin Tech Inc
    email: sales@penguintech.io
    url: https://penguintech.io
keywords:
  - hypervisor
  - automation
  - maas
  - bare-metal
  - provisioning
  - fleet-management
  - monitoring
sources:
  - https://github.com/penguintechinc/gough
dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.15.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: mysql
    version: "9.14.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: prometheus
    version: "25.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "7.0.8"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: logging.elasticsearch.enabled
  - name: kibana
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: logging.kibana.enabled
  - name: nginx-ingress
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.nginx.enabled
annotations:
  category: Infrastructure
  licenses: AGPL-3.0