---
# OSQuery Installation Role - Handlers

- name: restart osqueryd
  systemd:
    name: osqueryd
    state: restarted
    daemon_reload: true

- name: reload systemd
  systemd:
    daemon_reload: true

- name: stop osqueryd
  systemd:
    name: osqueryd
    state: stopped

- name: start osqueryd
  systemd:
    name: osqueryd
    state: started

- name: enable osqueryd
  systemd:
    name: osqueryd
    enabled: true